One Attestation API
LF-Decentralized-Trust-labs/LF-Decentralized-Trust-labs.github.io pull request #295
Opened 2024-11-26 00:50 UTC by bvavala

This lab proposes to create a single API to handle remote attestations.
Attestations are a crucial mechanism to establish trust in hardware-based trusted execution environments (TEEs).
Today, multiple attestation mechanisms are available, like SGX-EPID (which is being phased out), SGX-DCAP, TDX-DCAP and SEV-attestation.
This proposal aims to create a single abstraction for the generation and verification of hardware-based attestations.
The abstraction can benefit, and avoid redundant implementations in, multiple projects (e.g., Fabric Private Chaincode, Private Data Objects) that use TEEs to enhance software integrity and confidentiality.

2024-11-26 00:50 UTC, bvavala commented
@mbrandenburger Please acknowledge the sponsorship.

2024-11-26 07:57 UTC, mbrandenburger commented
I am happy to sponsor this lab!

Moreover, we plan to integrate this attestation library into the Fabric Private Chaincode project and thereby enable DCAP-based attestation. 🚀

2024-11-26 08:00 UTC, mbrandenburger commented
Note that this proposal is a "re-open" of #255.

2024-12-02 17:41 UTC, tkuhrt requested changes

2024-12-02 17:41 UTC, tkuhrt commented on labs/lfdt/one-attestation-api.md
> +parent: Labs
```suggestion
parent: LFDT Labs
grand_parent: Active Labs
```

2024-12-02 17:41 UTC, tkuhrt commented on labs/lfdt/one-attestation-api.md
> +Initially, we anticipate to integrate this tool in two Hyperledger projects: Fabric Private Chaincode and Private Data Objects.
```suggestion
Initially, we anticipate to integrate this tool with: Fabric Private Chaincode and Private Data Objects.
```

2024-12-03 07:33 UTC, bvavala commented on labs/lfdt/one-attestation-api.md
> +parent: Labs
Thank you Tracy!

2024-12-03 07:33 UTC, bvavala commented on labs/lfdt/one-attestation-api.md
> +Initially, we anticipate to integrate this tool in two Hyperledger projects: Fabric Private Chaincode and Private Data Objects.
Thank you Tracy!

2024-12-03 14:59 UTC, tkuhrt commented
@bvavala : Can you correct the DCO on the last two commits?

2024-12-03 17:07 UTC, bvavala commented
> @bvavala : Can you correct the DCO on the last two commits?

Done

2024-12-03 17:09 UTC, tkuhrt approved these changes

2024-12-03 17:16 UTC, alvaropicazo approved these changes

2024-12-03 17:26 UTC, merged

2024-12-05 08:27 UTC, mbrandenburger commented
🎉